/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dummyProxySol from "./DummyProxy.sol";
export type { dummyProxySol };
export type { MockBancorNetworkV3 } from "./MockBancorNetworkV3";
export type { TestBNT } from "./TestBNT";
export type { TestCarbonController } from "./TestCarbonController";
export type { TestERC20Burnable } from "./TestERC20Burnable";
export type { TestERC20FeeOnTransfer } from "./TestERC20FeeOnTransfer";
export type { TestERC20Token } from "./TestERC20Token";
export type { TestExpDecayMath } from "./TestExpDecayMath";
export type { TestLogic } from "./TestLogic";
export type { TestMathEx } from "./TestMathEx";
export type { TestOnlyProxyDelegate } from "./TestOnlyProxyDelegate";
export type { TestPairs } from "./TestPairs";
export type { TestReenterCarbonPOL } from "./TestReenterCarbonPOL";
export type { TestReenterCarbonVortex } from "./TestReenterCarbonVortex";
export type { TestReentrantToken } from "./TestReentrantToken";
export type { TestStrategies } from "./TestStrategies";
export type { TestTokenType } from "./TestTokenType";
export type { TestUpgradeable } from "./TestUpgradeable";
export type { TestVault } from "./TestVault";
export type { TestVoucher } from "./TestVoucher";
