/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as carbonControllerSol from "./CarbonController.sol";
export type { carbonControllerSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Pairs } from "./Pairs";
export type { Strategies } from "./Strategies";
