/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OptimizedTransparentUpgradeableProxyAccess } from "./OptimizedTransparentUpgradeableProxyAccess";
export type { ProxyAdminAccess } from "./ProxyAdminAccess";
