/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OptimizedTransparentUpgradeableProxyAccess__factory } from "./OptimizedTransparentUpgradeableProxyAccess__factory";
export { ProxyAdminAccess__factory } from "./ProxyAdminAccess__factory";
